import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatAllRemindersHuman } from "@/lib/medications/formatMedicationReminder";
import type { MedicationEntry } from "@/lib/medications/types";

const DISCLAIMER =
  "Generated by Recast from your document and conversation. Not medical advice. Confirm all medications and timing with your clinician or pharmacist.";

function sortByName(a: MedicationEntry, b: MedicationEntry): number {
  return a.name.localeCompare(b.name, undefined, { sensitivity: "base" });
}

function groupMedications(medications: MedicationEntry[]) {
  const current: MedicationEntry[] = [];
  const newOnes: MedicationEntry[] = [];
  const unspecified: MedicationEntry[] = [];
  for (const m of medications) {
    const r = m.listRole ?? "unspecified";
    if (r === "current") current.push(m);
    else if (r === "new") newOnes.push(m);
    else unspecified.push(m);
  }
  current.sort(sortByName);
  newOnes.sort(sortByName);
  unspecified.sort(sortByName);
  return { current, newOnes, unspecified };
}

function rowForMed(m: MedicationEntry): string[] {
  const when = formatAllRemindersHuman(m.reminders);
  return [
    m.name,
    m.dosage?.trim() || "—",
    m.instructions?.trim() || "—",
    when.trim() || "Not specified — add timing with your care team if needed.",
  ];
}

type Section = { title: string; meds: MedicationEntry[] };

/** Builds a printable medication list PDF (client-side). */
export function buildMedicationListPdfBlob(medications: MedicationEntry[]): Blob {
  const { current, newOnes, unspecified } = groupMedications(medications);
  const sections: Section[] = [
    { title: "Current medications", meds: current },
    { title: "New or suggested medications", meds: newOnes },
    { title: "Additional medications (role not specified in document)", meds: unspecified },
  ].filter((s) => s.meds.length > 0);

  const doc = new jsPDF({ unit: "mm", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  let cursorY = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Medication list", margin, cursorY);
  cursorY += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const stamp = new Date().toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
  doc.text(`Generated: ${stamp}`, margin, cursorY);
  cursorY += 12;

  const pageH = doc.internal.pageSize.getHeight();

  for (let s = 0; s < sections.length; s++) {
    const section = sections[s];
    if (cursorY > pageH - 36) {
      doc.addPage();
      cursorY = 20;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(section.title, margin, cursorY);
    cursorY += 9;

    const body = section.meds.map(rowForMed);
    autoTable(doc, {
      startY: cursorY,
      head: [["Medication", "Dosage", "Instructions", "When to take"]],
      body,
      theme: "striped",
      styles: { fontSize: 9, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: [55, 65, 81], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        0: { cellWidth: 42 },
        1: { cellWidth: 32 },
        2: { cellWidth: 48 },
        3: { cellWidth: 52 },
      },
      margin: { left: margin, right: margin },
    });

    const d = doc as jsPDF & { lastAutoTable?: { finalY: number } };
    cursorY = (d.lastAutoTable?.finalY ?? cursorY) + 14;
  }

  const d = doc as jsPDF & { lastAutoTable?: { finalY: number } };
  const lastY = d.lastAutoTable?.finalY ?? cursorY;
  let footY = lastY + 10;
  if (footY > pageH - 22) {
    doc.addPage();
    footY = 20;
  }
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  doc.setTextColor(90, 90, 90);
  const split = doc.splitTextToSize(DISCLAIMER, pageW - margin * 2);
  doc.text(split, margin, footY);

  return doc.output("blob");
}
